/* Auto-generated by genmsg_cpp for file /home/vibek/QRcode_detection/msg/Landmark.msg */
#ifndef QRCODE_DETECTION_MESSAGE_LANDMARK_H
#define QRCODE_DETECTION_MESSAGE_LANDMARK_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace QRcode_detection
{
template <class ContainerAllocator>
struct Landmark_ {
  typedef Landmark_<ContainerAllocator> Type;

  Landmark_()
  : x(0.0)
  , y(0.0)
  , name()
  {
  }

  Landmark_(const ContainerAllocator& _alloc)
  : x(0.0)
  , y(0.0)
  , name(_alloc)
  {
  }

  typedef float _x_type;
  float x;

  typedef float _y_type;
  float y;

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  name;


  typedef boost::shared_ptr< ::QRcode_detection::Landmark_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::QRcode_detection::Landmark_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct Landmark
typedef  ::QRcode_detection::Landmark_<std::allocator<void> > Landmark;

typedef boost::shared_ptr< ::QRcode_detection::Landmark> LandmarkPtr;
typedef boost::shared_ptr< ::QRcode_detection::Landmark const> LandmarkConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::QRcode_detection::Landmark_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::QRcode_detection::Landmark_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace QRcode_detection

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::QRcode_detection::Landmark_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::QRcode_detection::Landmark_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::QRcode_detection::Landmark_<ContainerAllocator> > {
  static const char* value() 
  {
    return "4645b6c5a4695eab51273d7976682e13";
  }

  static const char* value(const  ::QRcode_detection::Landmark_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x4645b6c5a4695eabULL;
  static const uint64_t static_value2 = 0x51273d7976682e13ULL;
};

template<class ContainerAllocator>
struct DataType< ::QRcode_detection::Landmark_<ContainerAllocator> > {
  static const char* value() 
  {
    return "QRcode_detection/Landmark";
  }

  static const char* value(const  ::QRcode_detection::Landmark_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::QRcode_detection::Landmark_<ContainerAllocator> > {
  static const char* value() 
  {
    return "#X-Y coordinates of waypoint in METERS\n\
# I think we can get meters/pixels out of the OccupancyGrid \n\
# if we need to convert\n\
float32 x\n\
float32 y\n\
\n\
string name\n\
\n\
";
  }

  static const char* value(const  ::QRcode_detection::Landmark_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::QRcode_detection::Landmark_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.x);
    stream.next(m.y);
    stream.next(m.name);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Landmark_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::QRcode_detection::Landmark_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::QRcode_detection::Landmark_<ContainerAllocator> & v) 
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
  }
};


} // namespace message_operations
} // namespace ros

#endif // QRCODE_DETECTION_MESSAGE_LANDMARK_H

